nacos:
  config:
    # 主配置服务器地址
    server-addr: 10.104.10.201:8848
    namespace: 1035e474-6605-4f58-af44-f97de4d5a346
    group: dev
    # 主配置 配置文件类型
    type: yaml
    # 主配置 data-id
    data-id: fast-testing.yaml
    # 主配置 开启自动刷新
    auto-refresh: true
    bootstrap:
      # bootstrap.enable=true，开启配置预加载功能
      enable: true
    # 主配置 最大重试次数
    max-retry: 10
    # 主配置 配置监听长轮询超时时间
    config-long-poll-timeout: 46000
    # 主配置 重试时间
    config-retry-time: 2333
    # 主配置 开启注册监听器预加载配置服务（除非特殊业务需求，否则不推荐打开该参数）
    enable-remote-sync-config: true
    ext-config:
      -   auto-refresh: true
          config-long-poll-timeout: 46000
          config-retry-time: 2333
          data-id: fast-testing.yaml
          enable-remote-sync-config: true
          group: dev
          max-retry: 10
          type: yaml
