management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'
server:
  servlet:
    context-path: /
  port: 8888
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: fast-testing
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    #缓冲的配置
    cache: false
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      exclude: static/**,templates/**
  redis:
    redisson:
      config: classpath:redisson_cluster.yml
  datasource:
    url: jdbc:sqlite::resource:db1.sqlite
    driver-class-name: org.sqlite.JDBC
    username:
    password:
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  # 关闭mybatis-plus的banner打印
  global-config:
    banner: false
  type-aliases-package: com.nutcracker.mapper
# logback config
logging:
  config: classpath:log4j2.xml
app:
  version: '@version@'
  secret:
    pool-size: 3

locks:
  zookeeper:                            # zookeeper分布式锁
#    connect-server: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181    # 连接地址
    connect-server: zookeeper01:2181    # 连接地址
    base-sleep-time-ms: 1000            # 每次重试时间间隔，单位毫秒
    max-retries: 3                      # 重试次数
    connection-timeout: 30000           # 连接超时时间,30秒
    session-timeout: 30000              # session会话超时时间,30秒