management:
  endpoints:
    web:
      base-path: /rest/actuator
      exposure:
        include: '*'
server:
  servlet:
    context-path: /secret-util
  port: 8888
spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 200MB
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  application:
    name: secret-util
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /templates/
      suffix: .html
  thymeleaf:
    #缓冲的配置
    cache: false
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      exclude: static/**,templates/**
  redis:
    redisson:
      config: classpath:redisson_cluster.yml
springdoc:
  version: '@version@'
  api-docs:
    # enabled the /v3/api-docs endpoint
    enabled: true
    # 布尔值。在@Schema（名称name、标题title和说明description，三个属性）上启用属性解析程序。
    resolve-schema-properties: true
  #    path: /site-tools.html
  swagger-ui:
    # 布尔值。控制“试用”请求的请求持续时间（毫秒）的显示。
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    # 布尔值。禁用swagger用户界面默认petstore url。（从v1.4.1开始提供）。
    disable-swagger-default-url: true
    # 是否开启默认根访问swagger
    use-root-path: false
    #自定义swagger前端请求路径，输入http：127.0.0.1:8080/doc会自动重定向到swagger页面
    path: /doc.html
    # 布尔值。控制供应商扩展（x-）字段和操作、参数和架构值的显示。
    show-extensions: true
    # 布尔值。控制参数的扩展名（pattern、maxLength、minLength、maximum、minminimum）字段和值的显示。
    show-common-extensions: true
  show-actuator: true
  # 包扫描路径
  # packages-to-scan: com.nutcracker.web.controller
  # 布尔值。实现OpenApi规范的打印。
  writer-with-default-pretty-printer: true
# logback config
logging:
  config: classpath:log4j2.xml
app:
  version: '@version@'
  secret:
    pool-size: 3

locks:
  zookeeper:                            # zookeeper分布式锁
#    connect-server: zookeeper01:2181,zookeeper02:2181,zookeeper03:2181    # 连接地址
    connect-server: zookeeper01:2181    # 连接地址
    base-sleep-time-ms: 1000            # 每次重试时间间隔，单位毫秒
    max-retries: 3                      # 重试次数
    connection-timeout: 30000           # 连接超时时间,30秒
    session-timeout: 30000              # session会话超时时间,30秒